INSERT INTO TODO(ID,USERNAME,DESCRIPTION, DATE_TARGET, DONE)
VALUES(10001,'nidhish','Get AWS Certified',CURRENT_DATE(),false);

INSERT INTO TODO(ID,USERNAME,DESCRIPTION, DATE_TARGET, DONE)
VALUES(10002,'nidhish','Get Azure Certified',CURRENT_DATE(),false);

INSERT INTO TODO(ID,USERNAME,DESCRIPTION, DATE_TARGET, DONE)
VALUES(10003,'nidhish','Get GCP Certified',CURRENT_DATE(),false);

INSERT INTO TODO(ID,USERNAME,DESCRIPTION, DATE_TARGET, DONE)
VALUES(10004,'nidhish','Get DropOcean Certified',CURRENT_DATE(),false);

INSERT INTO TODO(ID,USERNAME,DESCRIPTION, DATE_TARGET, DONE)
VALUES(10005,'nidhish','Get Firebase Certified',CURRENT_DATE(),false);